import { useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { GasCertificateType } from "@/lib/gas-addons";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ApplianceFields, ApplianceData, emptyAppliance } from "./ApplianceFields";
import { WarningNoticeFields } from "./WarningNoticeFields";
import { TestingPurgingFields } from "./TestingPurgingFields";
import { toast } from "sonner";
import { Loader2, Plus, ArrowLeft, ArrowRight, Save } from "lucide-react";

interface GasCertificateFormProps {
  certificateType: GasCertificateType;
  onComplete: () => void;
  onCancel: () => void;
}

const STEPS = {
  landlord_gas_safety: ["Job Details", "Gas Checks", "Appliances", "Comments & Sign"],
  homeowner_gas_safety: ["Job Details", "Gas Checks", "Appliances", "Comments & Sign"],
  nd_gas_safety: ["Job Details", "Gas Checks", "Appliances", "Comments & Sign"],
  nd_gas_testing_purging: ["Job Details", "Testing & Purging", "Comments & Sign"],
  gas_warning_notice: ["Job Details", "Warning Details", "Comments & Sign"],
};

export function GasCertificateForm({ certificateType, onComplete, onCancel }: GasCertificateFormProps) {
  const { profile, user } = useAuth();
  const [step, setStep] = useState(0);
  const [saving, setSaving] = useState(false);

  const steps = STEPS[certificateType];

  // Form state
  const [jobDetails, setJobDetails] = useState({
    job_address_name: "", job_address: "", job_postcode: "", job_phone: "",
    customer_name: "", customer_company: "", customer_address: "", customer_postcode: "", customer_phone: "",
    inspection_date: new Date().toISOString().split("T")[0],
    next_inspection_due: "",
  });

  const [gasChecks, setGasChecks] = useState({
    emergency_control_accessible: false, gas_tightness_satisfactory: false,
    pipework_visual_satisfactory: false, equipotential_bonding: false,
    co_alarm_present: false, co_alarm_fitted: false, co_alarm_satisfactory: false,
  });

  const [appliances, setAppliances] = useState<ApplianceData[]>([{ ...emptyAppliance }]);

  const [warningData, setWarningData] = useState({
    classification: "", issue_type: "",
    actions_taken: "", actions_required: "",
    riddor_reported_11_1: false, riddor_reported_11_2: false,
  });

  const [testingData, setTestingData] = useState({
    test_method: "", test_pressure_mbar: "", stabilisation_period: "",
    test_duration: "", permitted_pressure_drop: "", actual_pressure_drop: "",
    strength_test_result: "", tightness_test_result: "", purge_completed: false,
  });

  const [comments, setComments] = useState("");
  const [issuedByName, setIssuedByName] = useState(profile?.full_name || "");

  const handleApplianceChange = (index: number, data: ApplianceData) => {
    const updated = [...appliances];
    updated[index] = data;
    setAppliances(updated);
  };

  const handleSave = async (status: "draft" | "issued") => {
    if (!user || !profile?.company_id) return;
    setSaving(true);

    try {
      const certData: Record<string, unknown> = {
        company_id: profile.company_id,
        engineer_id: user.id,
        certificate_type: certificateType,
        certificate_number: "", // Auto-generated by trigger
        status,
        ...jobDetails,
        inspection_date: jobDetails.inspection_date || new Date().toISOString().split("T")[0],
        next_inspection_due: jobDetails.next_inspection_due || null,
        comments,
        issued_by_name: issuedByName,
      };

      // Add type-specific fields
      if (["landlord_gas_safety", "homeowner_gas_safety", "nd_gas_safety"].includes(certificateType)) {
        Object.assign(certData, gasChecks);
      }
      if (certificateType === "gas_warning_notice") {
        Object.assign(certData, warningData);
      }
      if (certificateType === "nd_gas_testing_purging") {
        Object.assign(certData, {
          test_method: testingData.test_method || null,
          test_pressure_mbar: testingData.test_pressure_mbar ? Number(testingData.test_pressure_mbar) : null,
          stabilisation_period: testingData.stabilisation_period || null,
          test_duration: testingData.test_duration || null,
          permitted_pressure_drop: testingData.permitted_pressure_drop ? Number(testingData.permitted_pressure_drop) : null,
          actual_pressure_drop: testingData.actual_pressure_drop ? Number(testingData.actual_pressure_drop) : null,
          strength_test_result: testingData.strength_test_result || null,
          tightness_test_result: testingData.tightness_test_result || null,
          purge_completed: testingData.purge_completed,
        });
      }

      const { data: cert, error } = await supabase
        .from("gas_certificates")
        .insert(certData as any)
        .select()
        .single();

      if (error) throw error;

      // Insert appliances if applicable
      if (["landlord_gas_safety", "homeowner_gas_safety", "nd_gas_safety"].includes(certificateType) && appliances.length > 0) {
        const applianceRows = appliances.map((a, i) => ({
          certificate_id: cert.id,
          position: i + 1,
          location: a.location || null,
          appliance_type: a.appliance_type || null,
          make: a.make || null,
          model: a.model || null,
          flue_type: a.flue_type || null,
          appliance_inspected: a.appliance_inspected,
          operating_pressure_mbar: a.operating_pressure_mbar ? Number(a.operating_pressure_mbar) : null,
          heat_input_kw: a.heat_input_kw ? Number(a.heat_input_kw) : null,
          high_co_ppm: a.high_co_ppm ? Number(a.high_co_ppm) : null,
          high_co2_percent: a.high_co2_percent ? Number(a.high_co2_percent) : null,
          low_co_ppm: a.low_co_ppm ? Number(a.low_co_ppm) : null,
          low_co2_percent: a.low_co2_percent ? Number(a.low_co2_percent) : null,
          safety_devices_correct: a.safety_devices_correct,
          ventilation_satisfactory: a.ventilation_satisfactory,
          visual_condition_satisfactory: a.visual_condition_satisfactory,
          appliance_safe_to_use: a.appliance_safe_to_use,
        }));

        const { error: appError } = await supabase
          .from("gas_certificate_appliances")
          .insert(applianceRows);
        if (appError) throw appError;
      }

      toast.success(status === "issued" ? "Certificate issued successfully" : "Draft saved");
      onComplete();
    } catch (err: any) {
      toast.error(err.message || "Failed to save certificate");
    } finally {
      setSaving(false);
    }
  };

  const renderStepContent = () => {
    const currentStepName = steps[step];

    if (currentStepName === "Job Details") {
      return (
        <div className="space-y-4">
          <Card>
            <CardHeader><CardTitle className="text-base">Property / Job Address</CardTitle></CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div><Label>Name</Label><Input value={jobDetails.job_address_name} onChange={e => setJobDetails(d => ({ ...d, job_address_name: e.target.value }))} /></div>
              <div><Label>Phone</Label><Input value={jobDetails.job_phone} onChange={e => setJobDetails(d => ({ ...d, job_phone: e.target.value }))} /></div>
              <div className="md:col-span-2"><Label>Address</Label><Input value={jobDetails.job_address} onChange={e => setJobDetails(d => ({ ...d, job_address: e.target.value }))} /></div>
              <div><Label>Postcode</Label><Input value={jobDetails.job_postcode} onChange={e => setJobDetails(d => ({ ...d, job_postcode: e.target.value }))} /></div>
              <div><Label>Inspection Date</Label><Input type="date" value={jobDetails.inspection_date} onChange={e => setJobDetails(d => ({ ...d, inspection_date: e.target.value }))} /></div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader><CardTitle className="text-base">Customer Details</CardTitle></CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div><Label>Name</Label><Input value={jobDetails.customer_name} onChange={e => setJobDetails(d => ({ ...d, customer_name: e.target.value }))} /></div>
              <div><Label>Company</Label><Input value={jobDetails.customer_company} onChange={e => setJobDetails(d => ({ ...d, customer_company: e.target.value }))} /></div>
              <div className="md:col-span-2"><Label>Address</Label><Input value={jobDetails.customer_address} onChange={e => setJobDetails(d => ({ ...d, customer_address: e.target.value }))} /></div>
              <div><Label>Postcode</Label><Input value={jobDetails.customer_postcode} onChange={e => setJobDetails(d => ({ ...d, customer_postcode: e.target.value }))} /></div>
              <div><Label>Phone</Label><Input value={jobDetails.customer_phone} onChange={e => setJobDetails(d => ({ ...d, customer_phone: e.target.value }))} /></div>
            </CardContent>
          </Card>
        </div>
      );
    }

    if (currentStepName === "Gas Checks") {
      return (
        <Card>
          <CardHeader><CardTitle className="text-base">Gas Installation Checks</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            {[
              ["emergency_control_accessible", "Emergency control valve accessible"],
              ["gas_tightness_satisfactory", "Gas tightness test satisfactory"],
              ["pipework_visual_satisfactory", "Visual inspection of pipework satisfactory"],
              ["equipotential_bonding", "Equipotential bonding satisfactory"],
              ["co_alarm_present", "CO alarm present"],
              ["co_alarm_fitted", "CO alarm fitted to current standards"],
              ["co_alarm_satisfactory", "CO alarm in satisfactory condition"],
            ].map(([key, label]) => (
              <label key={key} className="flex items-center gap-3 text-sm">
                <Checkbox
                  checked={(gasChecks as any)[key]}
                  onCheckedChange={v => setGasChecks(g => ({ ...g, [key]: !!v }))}
                />
                {label}
              </label>
            ))}
          </CardContent>
        </Card>
      );
    }

    if (currentStepName === "Appliances") {
      return (
        <div className="space-y-4">
          {appliances.map((a, i) => (
            <ApplianceFields
              key={i}
              index={i}
              data={a}
              onChange={handleApplianceChange}
              onRemove={(idx) => setAppliances(prev => prev.filter((_, j) => j !== idx))}
              canRemove={appliances.length > 1}
            />
          ))}
          <Button variant="outline" onClick={() => setAppliances(prev => [...prev, { ...emptyAppliance }])}>
            <Plus className="h-4 w-4 mr-2" /> Add Appliance
          </Button>
        </div>
      );
    }

    if (currentStepName === "Warning Details") {
      return (
        <Card>
          <CardHeader><CardTitle className="text-base">Warning Notice Details</CardTitle></CardHeader>
          <CardContent>
            <WarningNoticeFields data={warningData} onChange={(f, v) => setWarningData(d => ({ ...d, [f]: v }))} />
          </CardContent>
        </Card>
      );
    }

    if (currentStepName === "Testing & Purging") {
      return (
        <Card>
          <CardHeader><CardTitle className="text-base">Testing & Purging</CardTitle></CardHeader>
          <CardContent>
            <TestingPurgingFields data={testingData} onChange={(f, v) => setTestingData(d => ({ ...d, [f]: v }))} />
          </CardContent>
        </Card>
      );
    }

    if (currentStepName === "Comments & Sign") {
      return (
        <Card>
          <CardHeader><CardTitle className="text-base">Comments & Signature</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Comments / Defects</Label>
              <Textarea value={comments} onChange={e => setComments(e.target.value)} placeholder="Enter any comments or defect details..." rows={4} />
            </div>
            {certificateType !== "gas_warning_notice" && (
              <div>
                <Label>Next Inspection Due</Label>
                <Input type="date" value={jobDetails.next_inspection_due} onChange={e => setJobDetails(d => ({ ...d, next_inspection_due: e.target.value }))} />
              </div>
            )}
            <div>
              <Label>Issued By (Engineer Name)</Label>
              <Input value={issuedByName} onChange={e => setIssuedByName(e.target.value)} />
            </div>
          </CardContent>
        </Card>
      );
    }

    return null;
  };

  return (
    <div className="space-y-6">
      {/* Step indicator */}
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        {steps.map((s, i) => (
          <span key={s} className={i === step ? "text-foreground font-medium" : ""}>
            {i > 0 && <span className="mx-1">›</span>}
            {s}
          </span>
        ))}
      </div>

      {renderStepContent()}

      {/* Navigation */}
      <div className="flex justify-between">
        <div className="flex gap-2">
          {step > 0 && (
            <Button variant="outline" onClick={() => setStep(s => s - 1)}>
              <ArrowLeft className="h-4 w-4 mr-2" /> Back
            </Button>
          )}
          <Button variant="ghost" onClick={onCancel}>Cancel</Button>
        </div>
        <div className="flex gap-2">
          {step < steps.length - 1 ? (
            <Button onClick={() => setStep(s => s + 1)}>
              Next <ArrowRight className="h-4 w-4 ml-2" />
            </Button>
          ) : (
            <>
              <Button variant="outline" onClick={() => handleSave("draft")} disabled={saving}>
                <Save className="h-4 w-4 mr-2" /> Save Draft
              </Button>
              <Button onClick={() => handleSave("issued")} disabled={saving}>
                {saving && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                Issue Certificate
              </Button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
