import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@2.0.0";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.2";
import { getCorsHeaders } from "../_shared/cors.ts";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

interface TicketRequest {
  issue_type: string;
  priority: string;
  affected_module: string;
  description: string;
  steps_to_reproduce?: string;
  is_recurring: boolean;
  page_url?: string;
  browser_info?: string;
  app_version?: string;
  attachment_urls?: { file_url: string; file_name: string; mime_type?: string; file_size?: number }[];
}

const VALID_ISSUE_TYPES = ["Bug", "Feature Request", "Access Issue", "Data Issue", "Performance", "Other"];
const VALID_PRIORITIES = ["Low", "Medium", "High", "Critical"];
const VALID_MODULES = ["Dashboard", "Sites", "F-Gas Systems", "Inspections", "Gas Log", "Gas Certificates", "Organisation", "Reports", "Documents", "Other"];

const handler = async (req: Request): Promise<Response> => {
  const corsHeaders = getCorsHeaders(req);
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Authenticate user
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const body: TicketRequest = await req.json();

    // Validate required fields
    if (!body.description || body.description.trim().length === 0) {
      return new Response(JSON.stringify({ error: "Description is required" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }
    if (!body.issue_type || !VALID_ISSUE_TYPES.includes(body.issue_type)) {
      return new Response(JSON.stringify({ error: "Invalid issue type" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }
    if (!body.priority || !VALID_PRIORITIES.includes(body.priority)) {
      return new Response(JSON.stringify({ error: "Invalid priority" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }
    if (body.affected_module && !VALID_MODULES.includes(body.affected_module)) {
      return new Response(JSON.stringify({ error: "Invalid affected module" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    // Length limits
    if (body.description.length > 5000 || (body.steps_to_reproduce && body.steps_to_reproduce.length > 3000)) {
      return new Response(JSON.stringify({ error: "Input exceeds maximum length" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    // Pull identity from DB (never trust client)
    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("full_name, email, company_id")
      .eq("user_id", user.id)
      .single();

    if (!profile || !profile.company_id) {
      return new Response(JSON.stringify({ error: "Profile not found or no company" }), {
        status: 400, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const { data: company } = await supabaseAdmin
      .from("companies")
      .select("name")
      .eq("id", profile.company_id)
      .single();

    const { data: rolesData } = await supabaseAdmin
      .from("user_roles")
      .select("role")
      .eq("user_id", user.id);

    const userRole = rolesData?.map((r: any) => r.role).join(", ") || "unknown";

    // Insert ticket (ticket_ref auto-generated by trigger)
    const { data: ticket, error: insertError } = await supabaseAdmin
      .from("support_tickets")
      .insert({
        ticket_ref: "TEMP", // trigger overwrites this
        company_id: profile.company_id,
        user_id: user.id,
        user_name: profile.full_name || user.email || "Unknown",
        user_email: profile.email || user.email || "",
        user_role: userRole,
        org_name: company?.name || "Unknown",
        issue_type: body.issue_type,
        priority: body.priority,
        affected_module: body.affected_module || null,
        description: body.description,
        steps_to_reproduce: body.steps_to_reproduce || null,
        is_recurring: body.is_recurring || false,
        page_url: body.page_url || null,
        browser_info: body.browser_info || null,
        app_version: body.app_version || null,
        metadata: {},
      })
      .select("id, ticket_ref")
      .single();

    if (insertError || !ticket) {
      console.error("Insert error:", insertError);
      return new Response(JSON.stringify({ error: "Failed to create ticket" }), {
        status: 500, headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    // Insert attachments if any
    if (body.attachment_urls && body.attachment_urls.length > 0) {
      const attachments = body.attachment_urls.map((a) => ({
        ticket_id: ticket.id,
        file_url: a.file_url,
        file_name: a.file_name,
        mime_type: a.mime_type || null,
        file_size: a.file_size || null,
      }));
      await supabaseAdmin.from("support_ticket_attachments").insert(attachments);
    }

    // Send email
    const supportEmail = Deno.env.get("SUPPORT_EMAIL");
    if (supportEmail) {
      const safe = {
        name: escapeHtml(profile.full_name || "Unknown"),
        email: escapeHtml(profile.email || user.email || ""),
        org: escapeHtml(company?.name || "Unknown"),
        role: escapeHtml(userRole),
        issueType: escapeHtml(body.issue_type),
        priority: escapeHtml(body.priority),
        module: escapeHtml(body.affected_module || "Not specified"),
        description: escapeHtml(body.description),
        steps: escapeHtml(body.steps_to_reproduce || "Not provided"),
        recurring: body.is_recurring ? "Yes" : "No",
        pageUrl: escapeHtml(body.page_url || "Not captured"),
        browser: escapeHtml(body.browser_info || "Not captured"),
        timestamp: new Date().toISOString(),
        ticketRef: ticket.ticket_ref,
      };

      const attachmentsList = body.attachment_urls?.map(a =>
        `<li><a href="${escapeHtml(a.file_url)}" style="color: #2563eb;">${escapeHtml(a.file_name)}</a></li>`
      ).join("") || "<li>None</li>";

      const emailHtml = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background-color: #f3f4f6;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    <div style="background-color: #0a2540; padding: 24px; text-align: center;">
      <h1 style="color: #ffffff; margin: 0; font-size: 22px;">🎫 Support Ticket ${safe.ticketRef}</h1>
      <p style="color: #94a3b8; margin: 8px 0 0; font-size: 14px;">Priority: ${safe.priority} | Type: ${safe.issueType}</p>
    </div>
    <div style="padding: 24px;">
      <h2 style="color: #0a2540; margin-top: 0; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">User Information</h2>
      <table style="width: 100%; border-collapse: collapse;">
        <tr><td style="padding: 6px 0; color: #6b7280; width: 140px;">Name</td><td style="padding: 6px 0; color: #111827; font-weight: 500;">${safe.name}</td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Email</td><td style="padding: 6px 0; color: #111827;"><a href="mailto:${safe.email}" style="color: #2563eb;">${safe.email}</a></td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Organisation</td><td style="padding: 6px 0; color: #111827; font-weight: 500;">${safe.org}</td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Role</td><td style="padding: 6px 0; color: #111827;">${safe.role}</td></tr>
      </table>

      <h2 style="color: #0a2540; margin-top: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Issue Details</h2>
      <table style="width: 100%; border-collapse: collapse;">
        <tr><td style="padding: 6px 0; color: #6b7280; width: 140px;">Issue Type</td><td style="padding: 6px 0; color: #111827;">${safe.issueType}</td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Priority</td><td style="padding: 6px 0; color: #111827; font-weight: 500;">${safe.priority}</td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Module</td><td style="padding: 6px 0; color: #111827;">${safe.module}</td></tr>
        <tr><td style="padding: 6px 0; color: #6b7280;">Recurring</td><td style="padding: 6px 0; color: #111827;">${safe.recurring}</td></tr>
      </table>

      <h2 style="color: #0a2540; margin-top: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Description</h2>
      <p style="color: #374151; white-space: pre-wrap; margin: 8px 0;">${safe.description}</p>

      <h2 style="color: #0a2540; margin-top: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Steps to Reproduce</h2>
      <p style="color: #374151; white-space: pre-wrap; margin: 8px 0;">${safe.steps}</p>

      <h2 style="color: #0a2540; margin-top: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Attachments</h2>
      <ul style="padding-left: 20px; margin: 8px 0;">${attachmentsList}</ul>

      <h2 style="color: #0a2540; margin-top: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px;">Context</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
        <tr><td style="padding: 4px 0; color: #6b7280; width: 140px;">Page URL</td><td style="padding: 4px 0; color: #111827;">${safe.pageUrl}</td></tr>
        <tr><td style="padding: 4px 0; color: #6b7280;">Browser</td><td style="padding: 4px 0; color: #111827;">${safe.browser}</td></tr>
        <tr><td style="padding: 4px 0; color: #6b7280;">Timestamp</td><td style="padding: 4px 0; color: #111827;">${safe.timestamp}</td></tr>
      </table>
    </div>
    <div style="background-color: #f9fafb; padding: 16px 24px; text-align: center; border-top: 1px solid #e5e7eb;">
      <p style="color: #6b7280; margin: 0; font-size: 12px;">FTrack Support Ticket System</p>
    </div>
  </div>
</body>
</html>`;

      try {
        await resend.emails.send({
          from: "FTrack Support <noreply@ftrack.uk>",
          to: [supportEmail],
          subject: `[${safe.ticketRef}] ${safe.issueType} - ${safe.priority} Priority`,
          html: emailHtml,
        });
      } catch (emailErr) {
        console.error("Failed to send support email:", emailErr);
        // Don't fail the ticket creation if email fails
      }
    }

    return new Response(JSON.stringify({ success: true, ticket_ref: ticket.ticket_ref }), {
      status: 200, headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error submitting support ticket:", error);
    return new Response(JSON.stringify({ error: "An error occurred" }), {
      status: 500, headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  }
};

serve(handler);
